### ISSUE TITLE
Lemon Pound Cake

### ISSUE THREAD

**Issue by stevenpollack** [theSurlyBakery/vorschung#27]
This closes out #20 since we have to move over to something a bit more scalable...

Adapted from [here](http://allrecipes.com/recipe/7424/lemon-poppy-seed-loaf/?internalSource=search%20result&referringContentType=search%20results&clickId=cardslot%2020):

Ingredients:

- Flour 375g
- Granulated Sugar 400g
- Margarine 170g
- Salt 4g
- Baking Powder 15g
- Applesauce 115g
- Lemon Juice 125g

Procedure:
- Preheat oven to 350 degrees F (175 degrees C). Heavily grease and flour two 9x5 inch loaf pans.
Sift together flour, baking soda, and salt. Set aside.
- In a large bowl, cream butter or margarine, and sugar until light and fluffy.
- Beat in eggs, one at a time.
- Mix lemon juice and yogurt together and add alternately with the sifted flour mixture to the butter mixture. Mix until just blended.
- Stir in lemon rind and poppy seeds.
- Pour mixture into prepared pans and smooth tops.
- Bake at 350 degrees F (175 degrees C) for 50 minutes or until browned and a knife inserted in the center comes out clean.
- Cool on rack for 15 minutes before turning out of pans.

**Comment by stevenpollack** [comment]
Proposed lazy changed to procedure:

- melt margarine and mix together all wet ingredients.
- mix together all dry ingredients in a separate bowl
- add wet to dry until just blended.
- pour into molds.

**Comment by stevenpollack** [comment]
The procedure change worked out, but now am going to decrease sugar:

1. assume applesauce to sugar makes a perfect replacement, which means that we can remove 115g of sugar.
2. introduce 8 vanilla sugar (which has a ~3:1 replacement).

So, let's try again with 400 - 115 - 25 = 265g sugar.

**Comment by stevenpollack** [comment]
Try again with

- 120g applesauce
- 200g sugar
- 24g vanilla sugar

and the 10-10-20 rotate-rotate-cool schedule (160C, convection).

**Comment by stevenpollack** [comment]
Tried this again without vanilla, and swapping cake flour 1-1 with all-purpose. Baked for 25 minutes, and then tried icing with 75g sugar + 15g lemon juice.

**Comment by stevenpollack** [comment]
Scale the batter by 1.25x, and portion 105g / brake.

Use 85/17, sugar/lemon combo.

**Comment by stevenpollack** [comment]
1. scaled the batter by another 1.5x and portioned 18 brakes at 100g/brake (with 74g left over). 
2. Used 100g:22g, powdered sugar:lemon juice with 1 tsp of glaze/brake (barely worked out).

prep times:
- dry ingredients: 12:13
- wet ingredients: 08:22
- mixing: 04:35
- portioning batter: 21:18
- arranging batter onto rack: 01:21
- first round of baking (timer for 15:00): 16:51
- second round of baking (timer for another 15:00):  8:48 
- getting the goods into the fridge: 4:43

baking notes:
- with 18 brakes, and rotation between bottom 1/3 and top 1/3, a 15-8 split ended up (slightly) burning the tops. Consider a 12-12..

**Comment by jonathanpollack** [comment]
Dry was updated to:
* 700 g cake flour

and the glaze:
* 125g powdered sugar
* 30g lemon juice

I'm going to close this out and add the recipe to the repo.
