### ISSUE TITLE
Chocolate Brake

### ISSUE THREAD

**Issue by stevenpollack** [theSurlyBakery/vorschung#28]
Adapted (and scaled down by 1/4) from [here](http://www.chowhound.com/recipes/chocolate-pound-cake-30894)

### Dry:
- 39g Cake flour (type 405)
- 66g Granulated Sugar
- 2g Vanilla Sugar
- 0g Baking Powder
- 1g Salt
- 0g instant coffee
- 17g Dutch Cocoa Powder

### Wet
- 43g rapeseed oil
- 40g applesauce
- 38g water

## Directions
- mix water and cocoa, whisking until smooth; set aside.
- mix dry ingredients
- combine wet ingredients, including cocoa mixture
- add wet to dry until just incorporated
- bake at 160ºC with convection (not sure how long, not sure which position either)

**Comment by stevenpollack** [comment]
this closes out #21 since we need that to scale out.

**Comment by jonathanpollack** [comment]
Check out [this](http://allrecipes.com/recipe/68436/vegan-brownies/?internalSource=hub%20recipe&referringId=1562&referringContentType=recipe%20hub&clickId=cardslot%2023) vegan brownie recipe.

**Comment by stevenpollack** [comment]
tried the brownie recipe, but mixed all dry ingredients together (instead of making a cocoa solution, and then mixing with dry). With slight modifications, the batter made 19 brownies at 100 +/- 1 g/brownie.

**Comment by stevenpollack** [comment]
PR #30 closes out the traditional brake, but the cake recipe has promise, will develop further.

**Comment by stevenpollack** [comment]
PR #38 introduces the dirty harry.
